boostcampwm-2022/web20-OAO

client/src/core/todo/todoList.ts
TodoList 클래스에서 Todo CRUD 관련 메서드 구현
- A
- description
- screenshot
- B
- 변경 전
- 변경 후
- C
- 고민과 질문
=> FEAT: todolist crud

client/vite.config.ts
=> FIX: vite top level await 가능하도록 esNext target으로 변경

.github/workflows/CLIENT_DEV_BUILD.yml, docker-compose.yml
- 개발서버 반영 안 되는 문제 해결
- top level await 해결
- docker-compose 파일 수정 (package 변경사항 반영)
- 고민과 질문
=> FIX: build error 수정

client/src/core/todo/todoList.ts
잠시 미루기 기능 시 Todo 상태가 WAIT로 변하지 않는 버그가 있어 이를 수정했습니다.
- #140
=> FIX: 잠시 미루기 기능 시 Todo 상태 업데이트 되지 않는 문제 해결 

client/src/core/todo/todoList.ts
- 잠시 미루기 기능으로 인한 Todo 상태 업데이트 되지 않는 버그 수정
=> RELEASE: 잠시 미루기 버그 수정

client/src/components/main/PostponeBox.tsx, client/src/components/main/TodoInteractionButton.tsx, client/src/components/main/TodoTimeText.tsx, client/src/container/Menubar.tsx, client/src/container/main/TodoStatus.tsx, client/src/container/main/TodoTimeInteraction.tsx, client/src/core/todo/todoList.ts, client/src/hooks/useActiveTodo.tsx, client/src/hooks/useButtonConfig.tsx, client/src/hooks/useDone.tsx, client/src/hooks/useElapsedTime.tsx, client/src/hooks/usePostpone.tsx, client/src/hooks/useTodoList.tsx, client/src/page/Main.tsx
=> FIX: elapsed time 0으로 초기화되는 버그 수정

client/src/util/Constants.ts
=> FIX: constant input type date에서 datetime-local로 수정

client/tsconfig.json
자동완성 이용시 절대경로 완성
VSCode 자동완성 이용시 절대경로를 완성해주지 않는 현상
자동완성시 절대경로 자동 지정
- 고민과 질문
=> chore: 자동완성 이용시 절대경로 완성

client/src/App.tsx, client/src/util/GlobalState.ts
=> fix: 튜토리얼 중 컨트롤 바 메인 페이지에서 사라지지 않는 버그 수정 resolve #195

client/src/App.tsx
=> fix: 튜토리얼 중입니다 글씨의 글씨체, 사이즈, 색깔 수정

client/src/container/main/TodoStatus.tsx, client/src/images/Relaxing.tsx
- 커피 연기 애니메이션 추가
https://user-images.githubusercontent.com/39304306/206431853-143dfa9f-f1d8-488d-83fa-a7959682922f.mov
- 고민과 질문
- 시계바늘 돌리는거 힘들어요..
#194
=> FEAT: main page 커피 연기 애니메이션 추가

client/src/App.tsx, client/src/util/GlobalState.ts
https://user-images.githubusercontent.com/103937206/206432415-e7e3a644-7e5f-4c4e-bcd2-5b13b43bbce4.mov
=> fix:  튜토리얼 중 새로고침 시 redirection 기능 추가

client/src/components/diagram/TodoBlock.tsx, client/src/components/diagram/TodoVertex.tsx, client/src/container/diagram/Diagram.tsx, client/src/util/GlobalStyle.tsx, client/src/util/diagram.util.ts
애니메이션 구현
- 애니메이션을 구현하기 위해 Todo들을 관리하는 상태를 `aniState`를 가지는 오브젝트로 한번 더 래핑함.
- 데이터 업데이트 시점마다 기존 데이터와 비교해서 각 항목들의 `aniState`를 결정
-  `aniState`가 `mount` 혹은 `unmount`인 경우 `setTimeout`으로 일정 시간 후 데이터를 삭제하거나, 상태를 바꾸어주도록 구현.
- `setTimeout`이 중첩되는 문제를 피하기 위해, `setTimeout`역시 `aniState` 옆에 보관하고 있다가 새로운 상태 변화시에 `clearTimeout`을 호출 하도록 함.
- 고민과 질문
- 처음엔 `keyframes`로 구현하였으나, `keyframes`는 프레임 중간에 재생 방향을 바꿀 수 없음.
- 결국 transition으로 변경. 초기화 후 delay 0ms의 setTimeout으로 Mounting 애니메이션 추가
- #213
=> 213 micro feat 다이어그램 뷰 애니메이션 추가

client/src/components/main/TodoTimeText.tsx, client/src/container/TodoController.tsx, client/src/page/Main.tsx, client/src/util/GlobalState.ts
- modalTypeAtom 제거
- elapsed time 초기 실행 시 동기화되지 않는 문제 해결
- elapsed time 초기 실행 시 동기화되지 않는 문제 해결
- 불필요한 전역상태 제거
- props로 대체하여 불필요한 modalTypeAtom 제거
- 고민과 질문
#230
=> FIX: elapsed time 버그 수정 및 불필요한 전역상태 제거

client/src/components/Search.tsx, client/src/components/SearchBar.tsx, client/src/components/SearchListContent.tsx, client/src/components/todos/LabeledInput.tsx, client/src/components/todos/RelatedTodoInput.tsx, client/src/hooks/useModalComplete.ts
- SearchBar에서 특수문자 검색창 입력 안되게 처리
- .*+?^${}() 를 가진 todo의 title은 create&edit 할 수 없게 Error처리
- SearchListContent에서 state가 DONE인 Todo의 title은 텍스트 가운데 줄긋기 처리
- 고민과 질문
- #233
=> FIX: searchbar에서 특수문자 검색창 입력 안되게 처리

.github/workflows/CLIENT_BUILD.yml, .github/workflows/CLIENT_DEV_BUILD.yml, .github/workflows/PRODUCTION_RELEASE.yml, .github/workflows/PROXY_BUILD.yml, .github/workflows/PROXY_DEV_BUILD.yml, .github/workflows/SERVER_BUILD.yml, .github/workflows/SERVER_DEV_BUILD.yml, .github/workflows/TEST_REPORT.yml, docker-compose.production.yml, nginx/Dockerfile.production, nginx/default.production.conf
=> FIX: GitHub action 최적화 및 ssh 적용 

.github/workflows/CLIENT_BUILD.yml, .github/workflows/CLIENT_DEV_BUILD.yml
=> FIX: github actions 수행시 client TimeZone 설정

client/src/hooks/useModalComplete.ts, client/src/util/modal.util.ts
- activeTodo가 없을 때도 updateElapsedTime을 수행하여 오류 발생함
- input check & get하는 부분들 수정
- 고민과 질문
#254
=> FIX: modal 제대로 동작하지 않는 오류 수정

README.md
=> DOCS: README 팀원 소개 및 기술스택 추가

.github/workflows/PROXY_BUILD.yml
=> env: Dockerfile 업로드 삭제

client/vercel.json
- vercel 배포를 위한 vercel 설정 파일 추가
- 네이버 클라우드에서 vercel로 배포 변경 중 루트 path가 아닌 다른 path 접속시 에러 발생 (SPA이기 때문에)
- ex) /todos
- vercel rewrites를 이용하여 /로 rewrite하게 설정 추가
- 고민과 질문
- #273
=> ENV: vercel 설정 파일 추가
